global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'esmh_backend'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'esmh_celery'
    static_configs:
      - targets: ['localhost:5555']
