"""
Trade Signal Model - IATS Integration
Tracks all signals generated by bots and AI for analysis
"""

from datetime import datetime
from enum import Enum
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, ForeignKey, Boolean, JSON, Text
)
from sqlalchemy.sql import func
from ..database import Base


class SignalType(str, Enum):
    """Signal Type"""
    BUY = "BUY"
    SELL = "SELL"
    STRONG_BUY = "STRONG_BUY"
    STRONG_SELL = "STRONG_SELL"
    HOLD = "HOLD"
    NEUTRAL = "NEUTRAL"


class SignalSource(str, Enum):
    """Signal Origin"""
    BOT = "BOT"
    AI_OVERSEER = "AI_OVERSEER"
    INDICATOR = "INDICATOR"
    USER = "USER"
    ENSEMBLE = "ENSEMBLE"


class TradeSignal(Base):
    """
    Trade Signal Model - IATS Signal Tracking
    
    Records all signals for machine learning and performance analysis
    Supports IATS ensemble decision making
    """
    
    __tablename__ = "trade_signals"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False, index=True)
    trade_id = Column(Integer, ForeignKey('trades.id'), nullable=True)
    
    # Signal Identity
    symbol = Column(String(50), nullable=False, index=True)
    signal_type = Column(String(30), nullable=False)  # BUY, SELL, etc.
    signal_source = Column(String(50), nullable=False)  # BOT, AI, USER
    
    # Signal Strength
    signal_strength = Column(Float, default=0.5)  # 0-1.0
    confidence_score = Column(Float, default=0.0)  # 0-1.0
    
    # Source Details
    source_bot_id = Column(String(100), nullable=True)
    source_bot_strategy = Column(String(50), nullable=True)
    source_indicator = Column(String(100), nullable=True)
    
    # Signal Components
    signal_components = Column(JSON, nullable=True)  # {"RSI": 0.8, "MA": 0.7, ...}
    signal_parameters = Column(JSON, nullable=True)  # Strategy parameters
    
    # Market Context
    market_price = Column(Float, nullable=False)
    market_regime = Column(String(50), nullable=True)
    volatility = Column(Float, nullable=True)
    volume = Column(Float, nullable=True)
    
    # Execution
    was_executed = Column(Boolean, default=False)
    execution_price = Column(Float, nullable=True)
    execution_slippage = Column(Float, nullable=True)
    
    # Performance Tracking
    signal_pnl = Column(Float, nullable=True)  # If executed
    signal_pnl_percent = Column(Float, nullable=True)
    was_profitable = Column(Boolean, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False, index=True)
    executed_at = Column(DateTime, nullable=True)
    
    def __repr__(self) -> str:
        return f"<TradeSignal symbol={self.symbol} type={self.signal_type} strength={self.signal_strength}>"
