CREATE SCHEMA IF NOT EXISTS trading;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
SET timezone = 'UTC';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO esmh;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA trading TO esmh;
